apiVersion: v1
kind: Pod
metadata:
  name: test-cubefs-pods
  namespace: default
  labels:
    role: test-cubefs-pods
spec:
  containers:
    - name: test-cubefs-pods
      image: alpine:3.20
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /workdir
          mountPropagation: HostToContainer
          name: mypvc
  restartPolicy: Always
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: ltptest
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ltptest
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: my-cfs-sc