apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cubefs-csi-controller
  namespace: kube-system
  labels:
    app: my-cubefs-csi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-cubefs-csi-controller
  template:
    metadata:
      name: my-cubefs-csi-controller
      labels:
        app: my-cubefs-csi-controller
    spec:
      serviceAccountName: my-cubefs-csi-controller-sa
      containers:
        # provisioner
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ADDRESS
              value: /csi/csi-controller.sock
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        # liveness probe
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.14.0
          args:
            - --csi-address=/csi/csi-controller.sock
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir

      restartPolicy: Always
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/mycubefs.csi.cubefs.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
          name: mountpoint-dir

      