apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-cfs-csi-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: my-cfs-csi-node
  template:
    metadata:
      labels:
        app: my-cfs-csi-node
    spec:
      schedulerName: my-cubefs-csi-controller-sa
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
      containers:
        # driver registrar
        - name: csi-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.12.0
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/mycubefs.csi.cubefs.com/csi.sock"
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.14.0
          args:
            - --csi-address=/csi/csi.sock
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/mycubefs.csi.cubefs.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: DirectoryOrCreate
          name: registration-dir
