apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-cfs-sc
provisioner: mycubefs.csi.cubefs.com
allowVolumeExpansion: false
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  masterAddr: "192.168.0.201:17010,192.168.0.202:17010,192.168.0.203:17010"
  owner: "csiuser"
  consulAddr: "192.168.0.201:8500"
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: mycubefs.csi.cubefs.com
spec:
  attachRequired: false
  podInfoOnMount: true